import {
  ForecastResult,
  ForecastAIExplanation,
  ForecastSummary,
  TimeSeriesMetadata,
  DecompositionResult,
  ModelBacktestScorecard,
} from './forecastTypes';

/**
 * Builds mathematical fallback explanation if backend / Gemini is unavailable
 */
export function buildMathematicalFallbackExplanation(
  metric: string,
  summary: ForecastSummary,
  metadata: TimeSeriesMetadata,
  decomposition: DecompositionResult,
  scorecard: ModelBacktestScorecard,
  warnings: string[]
): ForecastAIExplanation {
  const growthSign = summary.expectedGrowthPct >= 0 ? '+' : '';
  const dirText = summary.expectedGrowthPct > 0 ? 'increase' : summary.expectedGrowthPct < 0 ? 'decrease' : 'remain stable';

  const headline = `${metric} is projected to ${dirText} by ${growthSign}${summary.expectedGrowthPct}% over the next ${summary.forecastHorizon} ${summary.horizonUnit}.`;

  const executiveSummary = `Historical baseline of ${metric} concludes at ${summary.latestActualValue.toLocaleString()}, with model forecasting an end-horizon value of ${summary.finalPredictedValue.toLocaleString()} (${growthSign}${summary.expectedGrowthPct}% expected delta). The projection is generated by ${scorecard.modelName}, evaluated via chronological backtesting with a validation sMAPE of ${scorecard.smape}%.`;

  const historicalTrendNarrative = `Historical series exhibits an overall ${decomposition.trend} trajectory (annualized/span growth rate of ${decomposition.trendGrowthPct}%). ${decomposition.seasonalityExplanation}`;

  const forecastDirectionNarrative = `Forward projection demonstrates a net ${summary.expectedGrowthPct >= 0 ? 'positive' : 'negative'} shift of ${Math.abs(summary.expectedAbsoluteChange).toLocaleString()} ${metric} units across the ${summary.forecastHorizon}-${summary.horizonUnit} window.`;

  const modelSelectionNarrative = `${scorecard.modelName} was chosen as the optimal predictor because it minimized out-of-sample forecast error (MAE: ${scorecard.mae}, RMSE: ${scorecard.rmse}) during historical rolling-origin cross-validation.`;

  const uncertaintyNarrative = `Prediction bands reflect a statistical uncertainty interval expanding into future periods. The actual observed outcome may fluctuate within the calculated lower bound and upper bound.`;

  const limitationsNarrative = warnings.length > 0
    ? `Key analytical caveats: ${warnings.join(' ')} Structural business interventions or macro shocks may alter baseline trajectories.`
    : `Standard forecasting limitation: projections assume continuation of historical operating dynamics without major external disruptions.`;

  const recommendedActions = [
    `Monitor weekly actuals against the ${scorecard.modelName} upper/lower confidence envelope.`,
    `Track operational metrics supporting ${metric} to validate expected ${dirText} momentum.`,
    `Perform monthly model re-calibration as new transaction records arrive.`,
  ];

  return {
    headline,
    executiveSummary,
    historicalTrendNarrative,
    forecastDirectionNarrative,
    modelSelectionNarrative,
    uncertaintyNarrative,
    limitationsNarrative,
    recommendedActions,
  };
}

/**
 * Fetches AI explanation from the backend `/api/forecast/explain` endpoint
 */
export async function explainForecastWithAI(
  forecast: Omit<ForecastResult, 'aiExplanation'>
): Promise<ForecastAIExplanation> {
  const fallback = buildMathematicalFallbackExplanation(
    forecast.config.metricColumn,
    forecast.summary,
    forecast.metadata,
    forecast.decomposition,
    forecast.scorecard.find((s) => s.modelType === forecast.selectedModel) || forecast.scorecard[0],
    forecast.warnings
  );

  try {
    const payload = {
      targetMetric: forecast.config.metricColumn,
      frequency: forecast.config.frequency,
      horizon: forecast.config.horizon,
      selectedModel: forecast.selectedModelName,
      selectionReason: forecast.selectionReason,
      summary: forecast.summary,
      metadata: forecast.metadata,
      decomposition: forecast.decomposition,
      bestScorecard: forecast.scorecard.find((s) => s.modelType === forecast.selectedModel) || forecast.scorecard[0],
      allScorecards: forecast.scorecard.map((s) => ({
        modelName: s.modelName,
        mae: s.mae,
        rmse: s.rmse,
        smape: s.smape,
        isEligible: s.isEligible,
      })),
      confidenceRating: forecast.confidenceRating,
      confidenceRationale: forecast.confidenceRationale,
      warnings: forecast.warnings,
    };

    const response = await fetch('/api/forecast/explain', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      console.warn('Backend forecast explain endpoint returned non-200, using structured fallback.');
      return fallback;
    }

    const data = await response.json();
    if (data && data.headline && data.executiveSummary) {
      return {
        headline: data.headline,
        executiveSummary: data.executiveSummary,
        historicalTrendNarrative: data.historicalTrendNarrative || fallback.historicalTrendNarrative,
        forecastDirectionNarrative: data.forecastDirectionNarrative || fallback.forecastDirectionNarrative,
        modelSelectionNarrative: data.modelSelectionNarrative || fallback.modelSelectionNarrative,
        uncertaintyNarrative: data.uncertaintyNarrative || fallback.uncertaintyNarrative,
        limitationsNarrative: data.limitationsNarrative || fallback.limitationsNarrative,
        recommendedActions: data.recommendedActions || fallback.recommendedActions,
      };
    }

    return fallback;
  } catch (err) {
    console.warn('Failed to fetch AI forecast explanation from server, using mathematical fallback:', err);
    return fallback;
  }
}
