import { ReportTemplateDefinition, ReportTemplateId, ReportSectionType } from './reportTypes';

export const REPORT_TEMPLATES: Record<ReportTemplateId, ReportTemplateDefinition> = {
  executive_briefing: {
    id: 'executive_briefing',
    name: 'Executive Briefing',
    description: 'High-level synthesis designed for C-Suite and VP stakeholders with core KPIs, strategic findings, and actionable recommendations.',
    badge: 'Executive',
    iconName: 'Crown',
    defaultSections: [
      'executive_summary',
      'kpi_overview',
      'trend_charts',
      'forecast_outlook',
      'recommendations',
      'limitations_methodology',
    ],
    targetAudience: 'Executive Leadership, Board of Directors, Investors',
    estimatedPages: 3,
  },
  comprehensive_bi: {
    id: 'comprehensive_bi',
    name: 'Full Business Intelligence Report',
    description: 'Complete end-to-end analytical dossier containing data hygiene, detailed performance metrics, category breakdowns, anomalies, RCA, and forecasts.',
    badge: 'Comprehensive',
    iconName: 'FileText',
    defaultSections: [
      'executive_summary',
      'data_quality_audit',
      'kpi_overview',
      'trend_charts',
      'category_breakdown',
      'anomaly_deep_dive',
      'root_cause_analysis',
      'forecast_outlook',
      'recommendations',
      'limitations_methodology',
      'data_table',
    ],
    targetAudience: 'Department Heads, Lead Analysts, Operations Teams',
    estimatedPages: 6,
  },
  anomaly_risk: {
    id: 'anomaly_risk',
    name: 'Anomaly & Risk Intelligence Report',
    description: 'Risk-oriented inspection of statistical spikes, structural dips, outlier concentrations, and root driver segmentations.',
    badge: 'Risk & Audit',
    iconName: 'AlertTriangle',
    defaultSections: [
      'executive_summary',
      'kpi_overview',
      'anomaly_deep_dive',
      'root_cause_analysis',
      'recommendations',
      'limitations_methodology',
    ],
    targetAudience: 'Risk Managers, Compliance, Operations Leads',
    estimatedPages: 4,
  },
  forecast_outlook: {
    id: 'forecast_outlook',
    name: 'Forecasting & Predictive Outlook',
    description: 'Forward-looking strategic planning report featuring multi-model cross-validation, confidence interval bands, and scenario planning.',
    badge: 'Predictive',
    iconName: 'TrendingUp',
    defaultSections: [
      'executive_summary',
      'kpi_overview',
      'trend_charts',
      'forecast_outlook',
      'recommendations',
      'limitations_methodology',
    ],
    targetAudience: 'FP&A Analysts, Strategic Planners, Supply Chain',
    estimatedPages: 4,
  },
  data_quality_audit: {
    id: 'data_quality_audit',
    name: 'Data Quality & Hygiene Audit',
    description: 'Deep governance assessment inspecting missing value distributions, row duplicate signatures, type integrity, and remediation roadmap.',
    badge: 'Governance',
    iconName: 'ShieldCheck',
    defaultSections: [
      'executive_summary',
      'data_quality_audit',
      'data_table',
      'recommendations',
      'limitations_methodology',
    ],
    targetAudience: 'Data Engineers, Analytics Engineers, Data Governance',
    estimatedPages: 3,
  },
  custom_modular: {
    id: 'custom_modular',
    name: 'Custom Modular Report',
    description: 'Build your own custom report by selecting and organizing any analytical modules, custom charts, notes, and tables.',
    badge: 'Flexible',
    iconName: 'Sliders',
    defaultSections: [
      'executive_summary',
      'kpi_overview',
      'trend_charts',
      'recommendations',
    ],
    targetAudience: 'Any Team / Custom Workflows',
    estimatedPages: 3,
  },
};

export const SECTION_METADATA: Record<
  ReportSectionType,
  { name: string; description: string; icon: string; category: string }
> = {
  executive_summary: {
    name: 'Executive Summary',
    description: 'Grounded executive briefing with key findings, metric highlights, and strategic takeaways.',
    icon: 'Sparkles',
    category: 'Summary',
  },
  kpi_overview: {
    name: 'Key Performance Indicators (KPIs)',
    description: 'High-visibility metric scorecards with period-over-period delta and sparklines.',
    icon: 'Activity',
    category: 'Metrics',
  },
  trend_charts: {
    name: 'Trend & Time-Series Visuals',
    description: 'Interactive Recharts showing actual chronological trends, seasonal cycles, and volume.',
    icon: 'TrendingUp',
    category: 'Visuals',
  },
  category_breakdown: {
    name: 'Categorical & Dimension Breakdown',
    description: 'Performance distributions across top customer, product, regional, or channel segments.',
    icon: 'PieChart',
    category: 'Visuals',
  },
  data_table: {
    name: 'Detailed Analytical Data Table',
    description: 'Clean formatted tabular records with sorting, pagination, and numeric formatting.',
    icon: 'Table',
    category: 'Data',
  },
  anomaly_deep_dive: {
    name: 'Statistical Anomaly Deep-Dive',
    description: 'Identified spikes, sudden drops, and multi-method statistical outlier evidence.',
    icon: 'AlertCircle',
    category: 'Diagnostics',
  },
  root_cause_analysis: {
    name: 'Root Cause & Driver Decomposition',
    description: 'Mathematical dimension contribution analysis, period shifts, and formulated hypotheses.',
    icon: 'Compass',
    category: 'Diagnostics',
  },
  forecast_outlook: {
    name: 'Predictive Forecast & Horizon Bands',
    description: 'Chronologically backtested projections, model accuracy scorecard, and uncertainty bands.',
    icon: 'LineChart',
    category: 'Forecasting',
  },
  data_quality_audit: {
    name: 'Data Quality & Hygiene Scorecard',
    description: 'Evaluation of missingness, duplicate rows, data types, and critical issues.',
    icon: 'ShieldCheck',
    category: 'Governance',
  },
  recommendations: {
    name: 'Strategic & Operational Recommendations',
    description: 'Actionable, prioritized business recommendations grounded directly in findings.',
    icon: 'CheckSquare',
    category: 'Strategy',
  },
  limitations_methodology: {
    name: 'Limitations & Methodology Notes',
    description: 'Transparent disclosure of assumptions, unobserved variables, and statistical criteria.',
    icon: 'Info',
    category: 'Governance',
  },
  custom_markdown: {
    name: 'Custom Annotation / Commentary',
    description: 'Custom rich text or notes written by the analyst to accompany the report.',
    icon: 'Edit3',
    category: 'Custom',
  },
};
